$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: data-model-drift
image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04
conda_file: conda_yamls/env_cli.yml
description: Environment created from a Docker image plus Conda environment.